name: Node.js Build  Template

on:

  workflow_call:
    inputs:
      node-version:
        required: true
        type: string
        description: 'The Node.js version to use for the build.'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ inputs.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}

      - name: Install Dependencies
        run: npm install

   